### ISSUE TITLE
Add a section for handlebars helpers and mixins

### ISSUE THREAD

**Issue by mehulkar** [intuitivepixel/ember-components#3]
Both of these are useful and it would be awesome to have a definitive place for them. I started with the [Ember Plugins](//github.com/mochaleaf/ember-plugins) project a while back but wasn't able to finish it.

**Comment by mehulkar** [comment]
There's also @ahawkins' [Ember Addons](http://emberaddons.com/) ([github](https://github.com/ahawkins/emberaddons)). 

Maybe we can consolidate these projects?

**Comment by kumavis** [comment]
+1
